### ISSUE TITLE
UnboundLocalError: local variable 'save_path' referenced before assignment

### ISSUE THREAD

**Issue by blingsr** [dongjinkim9/InterFlow#2]
Hi! I am very interested in your work, but I have a problem：

995it [19:52,  1.20s/it, consistency_loss=0.000225, ib_loss=2.5, lr=0.0001, nll=
996it [19:52,  1.20s/it, consistency_loss=0.000225, ib_loss=2.5, lr=0.0001, nll=
996it [19:53,  1.20s/it, consistency_loss=0.000229, ib_loss=1.65, lr=0.0001, nll
997it [19:53,  1.21s/it, consistency_loss=0.000229, ib_loss=1.65, lr=0.0001, nll
997it [19:54,  1.21s/it, consistency_loss=0.00023, ib_loss=0.444, lr=0.0001, nll
998it [19:54,  1.21s/it, consistency_loss=0.00023, ib_loss=0.444, lr=0.0001, nll
998it [19:55,  1.21s/it, consistency_loss=0.000235, ib_loss=1.21, lr=0.0001, nll
999it [19:55,  1.21s/it, consistency_loss=0.000235, ib_loss=1.21, lr=0.0001, nll
999it [19:57,  1.21s/it, consistency_loss=0.000227, ib_loss=1, lr=0.0001, nll=-1
1000it [19:57,  1.20s/it, consistency_loss=0.000227, ib_loss=1, lr=0.0001, nll=-
1000it [19:57,  1.20s/it, consistency_loss=0.000227, ib_loss=1, lr=0.0001, nll=-1.65]
Traceback (most recent call last):
  File "/home/chenz/InterFlow/interflow/main.py", line 36, in <module>
    train(args)
  File "/home/chenz/InterFlow/interflow/train.py", line 154, in train
    artifact.add_file(save_path)
UnboundLocalError: local variable 'save_path' referenced before assignment

**Comment by dongjinkim9** [comment]
Hi. I update the codes now. 
Thanks for reporting problems while you run the code.
